DEVX-2212: Improved ccloud:get_service_account function
Clarified parameter checking.  Validated with the following attempts

(ccloud::get_service_account)
ccloud::get_service_account expects one parameter (API Key)

➜ (ccloud::get_service_account "JJCCOZ6TA7REL54R")
104205

➜ (ccloud::get_service_account "JJCCOZ6TA7REL54R-bad")
ERROR: Could not associate key JJCCOZ6TA7REL54R-bad to a service account. Verify your credentials, ensure the API key has a set resource type, and try again.

➜ (ccloud::get_service_account "JJCCOZ6TA7REL54R" stack-configs/java-service-account-131410.config)
WARN: ccloud::get_service_account function expects one parameter, received two
104205