DEVX-2212: Updated usages of ccloud::set_kafka_cluster_use
Added more specific named function and updated usage.  Validated with

➜ source utils/ccloud_library.sh; (ccloud::set_kafka_cluster_use_from_api_key "J5E6NXBKDCJVKHTT" stack-configs/java-service-account-57744.config)
WARN: ccloud::set_kafka_cluster_use_from_api_key function expects one parameter, received two
Set Kafka cluster "lkc-q579p" as the active cluster for environment "env-qpj7d".

Associated key J5E6NXBKDCJVKHTT to Confluent Cloud Kafka cluster lkc-q579p at pkc-4kgmg.us-west-2.aws.confluent.cloud:9092

➜ source utils/ccloud_library.sh; (ccloud::set_kafka_cluster_use_from_api_key "J5E6NXBKDCJVKHTT")
Set Kafka cluster "lkc-q579p" as the active cluster for environment "env-qpj7d".

Associated key J5E6NXBKDCJVKHTT to Confluent Cloud Kafka cluster lkc-q579p at pkc-4kgmg.us-west-2.aws.confluent.cloud:9092

➜ source utils/ccloud_library.sh; (ccloud::set_kafka_cluster_use_from_api_key "J5E6NXBKDCJVKHTT-bad")
ERROR: Could not associate key J5E6NXBKDCJVKHTT-bad to a Confluent Cloud Kafka cluster. Verify your credentials, ensure the API key has a set resource type, and try again.

➜ source utils/ccloud_library.sh; (ccloud::set_kafka_cluster_use "J5E6NXBKDCJVKHTT")
WARN: set_kafka_cluster_use is deprecated, use ccloud::set_kafka_cluster_use_from_api_key
Set Kafka cluster "lkc-q579p" as the active cluster for environment "env-qpj7d".

Associated key J5E6NXBKDCJVKHTT to Confluent Cloud Kafka cluster lkc-q579p at pkc-4kgmg.us-west-2.aws.confluent.cloud:9092

➜ source utils/ccloud_library.sh; (ccloud::set_kafka_cluster_use "J5E6NXBKDCJVKHTT" param-2)
WARN: set_kafka_cluster_use is deprecated, use ccloud::set_kafka_cluster_use_from_api_key
WARN: ccloud::set_kafka_cluster_use_from_api_key function expects one parameter, received two
Set Kafka cluster "lkc-q579p" as the active cluster for environment "env-qpj7d".

Associated key J5E6NXBKDCJVKHTT to Confluent Cloud Kafka cluster lkc-q579p at pkc-4kgmg.us-west-2.aws.confluent.cloud:9092